<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Methods: Exploring the Uncertain - 5.2: Bootstrap Confidence Intervals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./18-Bootstrap-Other-Stats.html" rel="next">
<link href="./16-Bootstrap-Dist.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./16-Bootstrap-Dist.html">Chapter 5: Interval Estimates</a></li><li class="breadcrumb-item"><a href="./17-Bootstrap-Confidence-Int.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">5.2: Bootstrap Confidence Intervals</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Methods: Exploring the Uncertain</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Chapter 4: Estimation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Estimation-MLE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.1: Maximum Likelihood Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-Estimation-MOM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.2: Method of Moments Estimates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-Properties-Estimators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.3: Properties of Estimators</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Chapter 5: Interval Estimates</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Bootstrap-Dist.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.1: Bootstrap Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-Bootstrap-Confidence-Int.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">5.2: Bootstrap Confidence Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-Bootstrap-Other-Stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.3: Bootstrapping Comparitive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-Parametric-CI-Means.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.4: Parametric Confidence Intervals for Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-Parametric-CI-Proportions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.5: Parametric Confidence Intervals for Proportions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Chapter 6: Hypothesis Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-Intro-Hypothesis-Tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.1: Introduction to Hypothesis Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-Permutation-Tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.2: Permutation Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-Hypothesis-Single-Population.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.3: Parametric Hypothesis Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-Hypothesis-Comparing-Two.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.4: Parametric Tests for Two Populations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-Error-Types-and-Power-of-Tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.5: Error Types and Power of Tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Intro-to-Vectors-Dataframes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fundamentals of Working with Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Overview-of-Plots.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">An Overview of Plotting Data in R</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#case-study-ozone-concentration-in-new-york-city" id="toc-case-study-ozone-concentration-in-new-york-city" class="nav-link active" data-scroll-target="#case-study-ozone-concentration-in-new-york-city">Case Study: Ozone Concentration in New York City</a>
  <ul class="collapse">
  <li><a href="#loading-nyc-ozone-data" id="toc-loading-nyc-ozone-data" class="nav-link" data-scroll-target="#loading-nyc-ozone-data">Loading NYC Ozone Data</a>
  <ul class="collapse">
  <li><a href="#summarizing-and-storing-the-data" id="toc-summarizing-and-storing-the-data" class="nav-link" data-scroll-target="#summarizing-and-storing-the-data">Summarizing and Storing the Data</a></li>
  </ul></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#question-1a" id="toc-question-1a" class="nav-link" data-scroll-target="#question-1a">Question 1a</a></li>
  <li><a href="#question-1b" id="toc-question-1b" class="nav-link" data-scroll-target="#question-1b">Question 1b</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#bootstrap-distribution-for-a-proportion" id="toc-bootstrap-distribution-for-a-proportion" class="nav-link" data-scroll-target="#bootstrap-distribution-for-a-proportion">Bootstrap Distribution for a Proportion</a>
  <ul class="collapse">
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#question-2a" id="toc-question-2a" class="nav-link" data-scroll-target="#question-2a">Question 2a</a></li>
  <li><a href="#question-2b" id="toc-question-2b" class="nav-link" data-scroll-target="#question-2b">Question 2b</a></li>
  <li><a href="#question-2c" id="toc-question-2c" class="nav-link" data-scroll-target="#question-2c">Question 2c</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparing-bootstrapping-to-clt" id="toc-comparing-bootstrapping-to-clt" class="nav-link" data-scroll-target="#comparing-bootstrapping-to-clt">Comparing Bootstrapping to CLT</a></li>
  <li><a href="#sec-fishing" id="toc-sec-fishing" class="nav-link" data-scroll-target="#sec-fishing">Interval and Point Estimates</a></li>
  <li><a href="#a-95-bootstrap-percentile-confidence-interval" id="toc-a-95-bootstrap-percentile-confidence-interval" class="nav-link" data-scroll-target="#a-95-bootstrap-percentile-confidence-interval">A 95% Bootstrap Percentile Confidence Interval</a>
  <ul class="collapse">
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#question-3a" id="toc-question-3a" class="nav-link" data-scroll-target="#question-3a">Question 3a</a></li>
  <li><a href="#question-3b" id="toc-question-3b" class="nav-link" data-scroll-target="#question-3b">Question 3b</a></li>
  <li><a href="#question-3c" id="toc-question-3c" class="nav-link" data-scroll-target="#question-3c">Question 3c</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#adjusting-the-confidence-level" id="toc-adjusting-the-confidence-level" class="nav-link" data-scroll-target="#adjusting-the-confidence-level">Adjusting the Confidence Level</a>
  <ul class="collapse">
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a>
  <ul class="collapse">
  <li><a href="#question-4a" id="toc-question-4a" class="nav-link" data-scroll-target="#question-4a">Question 4a</a></li>
  <li><a href="#question-4b" id="toc-question-4b" class="nav-link" data-scroll-target="#question-4b">Question 4b</a></li>
  <li><a href="#question-4c" id="toc-question-4c" class="nav-link" data-scroll-target="#question-4c">Question 4c</a></li>
  <li><a href="#question-4d" id="toc-question-4d" class="nav-link" data-scroll-target="#question-4d">Question 4d</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparing-two-independent-populations" id="toc-comparing-two-independent-populations" class="nav-link" data-scroll-target="#comparing-two-independent-populations">Comparing Two Independent Populations</a>
  <ul class="collapse">
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-5" id="toc-solution-to-question-5" class="nav-link" data-scroll-target="#solution-to-question-5">Solution to Question 5</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#case-study-smoking-and-birth-weights" id="toc-case-study-smoking-and-birth-weights" class="nav-link" data-scroll-target="#case-study-smoking-and-birth-weights">Case Study: Smoking and Birth Weights</a>
  <ul class="collapse">
  <li><a href="#loading-the-birth-weight-sample" id="toc-loading-the-birth-weight-sample" class="nav-link" data-scroll-target="#loading-the-birth-weight-sample">Loading the Birth Weight Sample</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a>
  <ul class="collapse">
  <li><a href="#solution-to-question-6" id="toc-solution-to-question-6" class="nav-link" data-scroll-target="#solution-to-question-6">Solution to Question 6</a></li>
  </ul></li>
  <li><a href="#cleaning-the-birth-weight-data" id="toc-cleaning-the-birth-weight-data" class="nav-link" data-scroll-target="#cleaning-the-birth-weight-data">Cleaning the Birth Weight Data</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a></li>
  <li><a href="#difference-in-two-independent-means" id="toc-difference-in-two-independent-means" class="nav-link" data-scroll-target="#difference-in-two-independent-means">Difference in Two Independent Means</a></li>
  <li><a href="#subsetting-the-sample" id="toc-subsetting-the-sample" class="nav-link" data-scroll-target="#subsetting-the-sample">Subsetting the Sample</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a>
  <ul class="collapse">
  <li><a href="#question-8a" id="toc-question-8a" class="nav-link" data-scroll-target="#question-8a">Question 8a</a></li>
  <li><a href="#question-8b" id="toc-question-8b" class="nav-link" data-scroll-target="#question-8b">Question 8b</a></li>
  <li><a href="#question-8c" id="toc-question-8c" class="nav-link" data-scroll-target="#question-8c">Question 8c</a></li>
  <li><a href="#question-8d" id="toc-question-8d" class="nav-link" data-scroll-target="#question-8d">Question 8d</a></li>
  </ul></li>
  <li><a href="#accounting-for-uncertainty-in-sampling" id="toc-accounting-for-uncertainty-in-sampling" class="nav-link" data-scroll-target="#accounting-for-uncertainty-in-sampling">Accounting for Uncertainty in Sampling</a></li>
  </ul></li>
  <li><a href="#bootstrapping-two-independent-samples" id="toc-bootstrapping-two-independent-samples" class="nav-link" data-scroll-target="#bootstrapping-two-independent-samples">Bootstrapping Two Independent Samples</a>
  <ul class="collapse">
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a>
  <ul class="collapse">
  <li><a href="#question-9a" id="toc-question-9a" class="nav-link" data-scroll-target="#question-9a">Question 9a</a></li>
  <li><a href="#question-9b" id="toc-question-9b" class="nav-link" data-scroll-target="#question-9b">Question 9b</a></li>
  <li><a href="#question-9c" id="toc-question-9c" class="nav-link" data-scroll-target="#question-9c">Question 9c</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#matched-pair-difference-comparing-two-dependent-samples" id="toc-matched-pair-difference-comparing-two-dependent-samples" class="nav-link" data-scroll-target="#matched-pair-difference-comparing-two-dependent-samples">Matched-Pair Difference: Comparing Two Dependent Samples</a></li>
  <li><a href="#case-study-darwin-cross-fertilization-experiments" id="toc-case-study-darwin-cross-fertilization-experiments" class="nav-link" data-scroll-target="#case-study-darwin-cross-fertilization-experiments">Case Study: Darwin Cross-Fertilization Experiments</a>
  <ul class="collapse">
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data">Loading the Data</a>
  <ul class="collapse">
  <li><a href="#summarizing-and-storing-the-data-1" id="toc-summarizing-and-storing-the-data-1" class="nav-link" data-scroll-target="#summarizing-and-storing-the-data-1">Summarizing and Storing the Data</a></li>
  </ul></li>
  <li><a href="#wranginling-the-data" id="toc-wranginling-the-data" class="nav-link" data-scroll-target="#wranginling-the-data">Wranginling the Data</a></li>
  <li><a href="#question-4-wetsuit-case-study" id="toc-question-4-wetsuit-case-study" class="nav-link" data-scroll-target="#question-4-wetsuit-case-study">Question 4: Wetsuit Case Study</a>
  <ul class="collapse">
  <li><a href="#question-4a-1" id="toc-question-4a-1" class="nav-link" data-scroll-target="#question-4a-1">Question 4a</a></li>
  <li><a href="#question-4b-1" id="toc-question-4b-1" class="nav-link" data-scroll-target="#question-4b-1">Question 4b</a></li>
  <li><a href="#question-4c-1" id="toc-question-4c-1" class="nav-link" data-scroll-target="#question-4c-1">Question 4c</a></li>
  <li><a href="#question-4d-1" id="toc-question-4d-1" class="nav-link" data-scroll-target="#question-4d-1">Question 4d</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">5.2: Bootstrap Confidence Intervals</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><a href="https://githubtocolab.com/CU-Denver-MathStats-OER/Statistical-Theory/blob/main/Chap5/17-Bootstrap-Confidence-Int.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid" alt="Open In Colab"></a> &nbsp;</p>
<p>In our <a href="./16-Bootstrap-Dist.html">work with bootstrap distributions</a>, we explored how we can used data from one random sample picked from a population with unknown parameters to construct an approximation for a sampling distribution. From a bootstrap distribution, we can define a new estimator:</p>
<ul>
<li>We defined the <span style="color:dodgerblue">estimator <span class="math inline">\(\hat{\theta}_{\rm{boot}}\)</span></span> as the mean (expected) value of the bootstrap distribution.</li>
<li>We use the <span style="color:dodgerblue">bootstrap standard error</span> to estimate the variability or uncertainty in estimates due to the randomness of sampling.</li>
<li>We defined the <span style="color:dodgerblue">bootstrap estimate of bias</span> as <span class="math inline">\(\mbox{Bias}_{\rm{boot}} \big( \hat{\theta}_{\rm{boot}} \big) = \hat{\theta}_{\rm{boot}} - \left( \mbox{observed sample statististic} \right)\)</span>.
<ul>
<li>For example, in the case of estimating a population mean <span class="math inline">\(\mu\)</span>, we have <span class="math inline">\({\color{dodgerblue}{\mbox{Bias}_{\rm{boot}} \big( \hat{\mu}_{\rm{boot}} \big) = \hat{\mu}_{\rm{boot}} - \bar{x}}}\)</span>.</li>
</ul></li>
</ul>
<p>In this section we will discuss how we can use the bootstrap standard error to account for the uncertainty in our estimate and to incorporate that uncertainty in our final estimate.</p>
<section id="case-study-ozone-concentration-in-new-york-city" class="level1">
<h1>Case Study: Ozone Concentration in New York City</h1>
<hr>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://www-f.nescaum.org/documents/listos/AQI_Map_170518.png" class="img-fluid figure-img" style="width:65.0%" alt="Map of Air Quality in Northeastern US"></p>
<figcaption class="figure-caption">Credit: <a href="https://www-f.nescaum.org/documents/listos">Northeast States for Coordinated Air Use Management (NESCAUM)</a></figcaption>
</figure>
</div>
<p>Accoording to the Unites States Environmental Protection Agency (EPA)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<blockquote class="blockquote">
<p>Ozone (O3) is a highly reactive gas composed of three oxygen atoms. It is both a natural and a man-made product that occurs in the Earth’s upper atmosphere (the stratosphere) and lower atmosphere (the troposphere). Depending on where it is in the atmosphere, ozone affects life on Earth in either good or bad ways.</p>
</blockquote>
<p>When the ozone concentration is greater, respiratory illnesses such as asthma, pneumonia, and bronchitis can become exacerbated. While the effects of short-term exposure to high ozone concentration are reversible, long-term exposure may not be reversible. The EPA sets Ozone National Ambient Air Quality Standards (NAAQS)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. “The existing primary and secondary standards, established in 2015, are 0.070 parts per million (ppm)”, or equivalently 70 parts per billion (pbb).</p>
<p>We will begin todays work with bootstrap distributions investigating the following question:</p>
<blockquote class="blockquote">
<p><strong>Is the population of New York City experiencing long-term exposure to unhealthy levels of ozone?</strong></p>
</blockquote>
<section id="loading-nyc-ozone-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-nyc-ozone-data">Loading NYC Ozone Data</h2>
<hr>
<p>It is very likely you do not have the package <code>lattice</code> installed. You will need to first install the <code>lattice</code> package.</p>
<ul>
<li>Go to the R Console window.</li>
<li>Run the command <code>&gt; install.packages("lattice")</code>.</li>
</ul>
<p>You will only need to run the <code>install.package()</code> command one time. You can now access <code>lattice</code> anytime you like! However, you will need to run the command <code>library(lattice)</code> during any R session in which you want to access data from the <code>lattice</code> package. <strong>Be sure you have first installed the <code>lattice</code> package before executing the code cell below.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># be sure you have already installed the lattice package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)  <span class="co"># loading permute package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="summarizing-and-storing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="summarizing-and-storing-the-data">Summarizing and Storing the Data</h3>
<hr>
<p>In the code cell below we summarize a data frame<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> named <code>environmental</code> from the <code>lattice</code> package and store the ozone concentration data <code>environmental$ozone</code> to a vector named <code>nyc.oz</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(environmental)  <span class="co"># numerical summary of each variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ozone         radiation      temperature         wind       
 Min.   :  1.0   Min.   :  7.0   Min.   :57.00   Min.   : 2.300  
 1st Qu.: 18.0   1st Qu.:113.5   1st Qu.:71.00   1st Qu.: 7.400  
 Median : 31.0   Median :207.0   Median :79.00   Median : 9.700  
 Mean   : 42.1   Mean   :184.8   Mean   :77.79   Mean   : 9.939  
 3rd Qu.: 62.0   3rd Qu.:255.5   3rd Qu.:84.50   3rd Qu.:11.500  
 Max.   :168.0   Max.   :334.0   Max.   :97.00   Max.   :20.700  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nyc.oz <span class="ot">&lt;-</span> environmental<span class="sc">$</span>ozone  <span class="co"># store ozone data to a vector</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<hr>
<p>We will use the sample data stored in <code>nyc.oz</code> to construct a bootstrap distribution that we can use to make predictions about the population of all times in New York City. Answer the questions below to get acquainted with the sample data.</p>
<section id="question-1a" class="level3">
<h3 class="anchored" data-anchor-id="question-1a">Question 1a</h3>
<hr>
<p>How many observations are in the sample stored in <code>nyc.oz</code>? Describe the shape of the data in <code>nyc.oz</code>.</p>
<section id="solution-to-question-1a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-1a">Solution to Question 1a</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-1b" class="level3">
<h3 class="anchored" data-anchor-id="question-1b">Question 1b</h3>
<hr>
<p>Based on the sample data in <code>nyc.oz</code>, give an estimate for the mean ozone concentration in New York City (over all days and times).</p>
<section id="solution-to-question-1b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-1b">Solution to Question 1b</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="bootstrap-distribution-for-a-proportion" class="level1">
<h1>Bootstrap Distribution for a Proportion</h1>
<hr>
<p>The sample mean for ozone concentration is below the 70 ppb limit. However, from the plot in <a href="#question-1a">Question 1a</a>, we see there are number of observations in the sample with an ozone concentration over 70 ppb.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>What proportion of time in NYC is the ozone concentration greater than 70 ppb?</p>
</blockquote>
<p>The sample proportion of observations with an ozone concentration greater than 70 pbb is <span class="math inline">\(24/111 \approx 0.2162\)</span>. We calculate the sample proportion in two different ways below. In both methods, we use the logical test <code>nyc.oz &gt; 70</code> to help count the number of observations greater than 70 pbb.</p>
<ol type="1">
<li>Using a logical test in a <code>sum()</code> command and dividing by the sample size <code>n</code>.</li>
<li>Using a logical test in a <code>mean()</code> command sums and divides by <span class="math inline">\(n\)</span> at once.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 1</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(nyc.oz)  <span class="co"># number of observations in sample</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>) <span class="sc">/</span> n  <span class="co"># sample proportion over 70 ppb</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2162162</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 2</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>)  <span class="co"># sample proportion over 70 ppb</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2162162</code></pre>
</div>
</div>
<p>Both methods are equivalent and we see that</p>
<p><span class="math display">\[\hat{p} = 0.2162 = 21.62 \%.\]</span> Thus use the plug-in principle, a reasonable estimate for the proportion of all time that the ozone concentration in NYC is over 70 ppb (we denote the population proportion <span class="math inline">\(p\)</span>) is</p>
<p><span class="math display">\[ p \approx \hat{p} = 0.2612.\]</span> How certain can we be in this estimate? If we pick another sample of observations, would we get a similar estimate for <span class="math inline">\(p\)</span>, or should we expect a lot of variability?</p>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<hr>
<p>Answer each part below to construct a bootstrap distribution for the sample proportion. Then use the result to answer the questions that follow.</p>
<section id="question-2a" class="level3">
<h3 class="anchored" data-anchor-id="question-2a">Question 2a</h3>
<hr>
<p>Complete the code cell below to construct a bootstrap distribution for the sample proportion of observations with ozone concentration greater than 70 ppb.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are two operations to complete inside the for loop:</p>
<ol type="1">
<li>Pick a bootstrap resample from the observed sample <code>nyc.oz</code>.</li>
<li>Calculate the proportion of observations in the bootstrap resample with ozone concentration greater than 70 ppb.</li>
</ol>
</div>
</div>
<section id="solution-to-question-2a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-2a">Solution to Question 2a</h4>
<hr>
<p>Replace all six <code>??</code> in the code cell below with appropriate code. Then run the completed code to generate a bootstrap distribution and mark the observed sample proportion (in red) and the mean of the bootstrap distribution (in blue) with vertical lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>boot.prop <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap proportions</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  boot.prop[i] <span class="ot">&lt;-</span> ??  <span class="co"># compute bootstrap sample proportion</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.prop,  </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p-hat, sample proportion"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Proportion"</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-2b" class="level3">
<h3 class="anchored" data-anchor-id="question-2b">Question 2b</h3>
<hr>
<p>Based on your answer to <a href="#question-2a">Question 2a</a>, calculate bootstrap estimate for bias. Note answers will vary due to the randomness of bootstrapping in <a href="#question-2a">Question 2a</a>.</p>
<section id="solution-to-question-2b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-2b">Solution to Question 2b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate bootstrap estimate of bias</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-2c" class="level3">
<h3 class="anchored" data-anchor-id="question-2c">Question 2c</h3>
<hr>
<p>Based on your answer to <a href="#question-2a">Question 2a</a>, calculate the bootstrap estimate for the standard error of the sampling distribution for sample proportions. Note answers will vary due to the randomness of bootstrapping in <a href="#question-2a">Question 2a</a>.</p>
<section id="solution-to-question-2c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-2c">Solution to Question 2c</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate bootstrap standard error</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="comparing-bootstrapping-to-clt" class="level1">
<h1>Comparing Bootstrapping to CLT</h1>
<hr>
<p>Recall the <a href="11-Sampling-Dist-Prop.qmd">Central Limit Theorem (CLT) for Proportions</a>,</p>
<p><span class="math display">\[\widehat{P} \sim N \left( \mu_{\hat{P}}, \mbox{SE}(\widehat{P}) \right) = \left( {\color{tomato}{p}}, \sqrt{\frac{{\color{tomato}{p}}(1-{\color{tomato}{p}})}{n}} \right).\]</span></p>
<p>The population proportion <span class="math inline">\(p\)</span> is unknown, but we can use the plug-in principle and use the sample proportion <span class="math inline">\({\color{tomato}{\hat{p} = 0.2162}}\)</span> in place to estimate the sampling distribution for the sample proportion:</p>
<p><span class="math display">\[\begin{aligned}
\widehat{P} \sim N \left( \mu_{\hat{P}}, \mbox{SE}(\widehat{P}) \right) &amp;= \left( {\color{tomato}{p}}, \sqrt{\frac{{\color{tomato}{p}}(1-{\color{tomato}{p}})}{n}} \right) \\
&amp; \approx N\left( {\color{tomato}{0.2162}}, \sqrt{\frac{{\color{tomato}{0.2162}}(1-{\color{tomato}{0.2162}})}{111}} \right) \\
&amp; \approx N( 0.2162, 0.0391).
\end{aligned}\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th>Method</th>
<th>Mean of Sampling Distribution</th>
<th>Standard Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bootstrap<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></td>
<td><span class="math inline">\(0.2164\)</span></td>
<td><span class="math inline">\(0.0390\)</span></td>
</tr>
<tr class="even">
<td>CLT with <span class="math inline">\(\hat{p}\)</span> in place of <span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(0.2162\)</span></td>
<td><span class="math inline">\(0.0391\)</span></td>
</tr>
</tbody>
</table>
<p>The two methods, bootstrap distribution and the estimate from using the CLT, give us consistent results!</p>
</section>
<section id="sec-fishing" class="level1">
<h1>Interval and Point Estimates</h1>
<hr>
<p>Usually when estimating an unknown population parameter, we give an <span style="color:dodgerblue"><strong>interval estimate</strong></span> that gives range of plausible values for the parameter by accounting for the uncertainty due to the variability in sampling.</p>
<ul>
<li>For example, using both mean and standard error from the bootstrap distribution in <a href="#question-2c">Question 2c</a>, we could say</li>
</ul>
<p><span class="math display">\[ p_{\rm over} \approx \hat{p}_{\rm boot} \color{dodgerblue}{\pm \mbox{SE}_{\rm boot} \left( \widehat{P} \right)} = 0.216 \color{dodgerblue}{\pm 0.039}.\]</span></p>
<ul>
<li><p>An interval of plausible values for <span class="math inline">\(p\)</span> is from <span class="math inline">\(0.177\)</span> to <span class="math inline">\(0.255\)</span>.</p></li>
<li><p>An estimate for a parameter with a single value is called a <span style="color:dodgerblue"><strong>point estimate</strong></span>.</p>
<ul>
<li>Since there is variability from sample to sample, it is not very likely that our point estimate is perfectly accurate, but it is likely close.</li>
<li>We get a very specific estimate that is very unlikely to equal the actual parameter value.</li>
<li><span style="color:tomato"><strong>This is like trying to catch a fish with a spear.</strong></span></li>
</ul></li>
<li><p>An estimate for a parameter with a range of values is called an <span style="color:dodgerblue"><strong>interval estimate</strong></span>.</p>
<ul>
<li>By building some uncertainty into our estimate, we can be more confident the actual value of the parameter is somewhere inside the interval.</li>
<li>However, our estimate is less specific.</li>
<li><span style="color:mediumseagreen"><strong>This is like trying to catch a fish with a net.</strong></span></li>
<li>We are more likely to catch fish even if we do not know specifically where the fish is!</li>
</ul></li>
<li><p><span style="color:dodgerblue"><strong>We frequently estimate parameters with interval to account for the variability of sample statistics.</strong></span></p></li>
</ul>
<div id="fig-fishing" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 47.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://i0.wp.com/pixahive.com/wp-content/uploads/2020/09/Man-Throwing-a-Fishing-Net-79117-pixahive.jpg?fit=778%2C518&amp;ssl=1" class="img-fluid figure-img" alt="Man Throwing a Fishing Net"></p>
<figcaption class="figure-caption">Credit: Rahil, <a href="https://creativecommons.org/share-your-work/public-domain/cc0/">Public Domain</a>, <a href="https://pixahive.com/photo/man-throwing-a-fishing-net/">Pixahive</a></figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 53.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://cdn2.picryl.com/photo/1898/12/31/fmib-48360-indian-sealing-canoe-showing-method-of-throwing-spear-7cbd5a-1024.jpeg" class="img-fluid figure-img" alt="Sealing Canoe Showing Method of Throwing Spear"></p>
<figcaption class="figure-caption">Credit: <a href="https://garystockbridge617.getarchive.net/amp/media/fmib-48360-indian-sealing-canoe-showing-method-of-throwing-spear-7cbd5a">Townsend, C. H</a>. (1898), Public Domain</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;9.1: Fishing with an interval estimate compared to a point estimate.</figcaption><p></p>
</figure>
</div>
</section>
<section id="a-95-bootstrap-percentile-confidence-interval" class="level1">
<h1>A 95% Bootstrap Percentile Confidence Interval</h1>
<hr>
<p>The interval between the <span class="math inline">\(2.5\)</span> and <span class="math inline">\(97.5\)</span> percentiles (or <span class="math inline">\(0.025\)</span> and <span class="math inline">\(0.975\)</span> quantiles) of the bootstrap distribution of a statistic is a <span style="color:dodgerblue"><strong>95% bootstrap percentile confidence interval</strong></span> for the corresponding parameter.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-confint" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="17-Bootstrap-Confidence-Int_files/figure-html/fig-confint-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;10.1: Finding Cutoffs for a 95% Bootstrap Percentile Confidence Interval</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>If most of the sample statistics are located in a certain interval of the bootstrap distribution, it seems plausible the true value of the parameter is in this interval!</li>
<li>We would say we are 95% confident that the interval contains the actual value of the population parameter since 95% of the bootstrap resamples are inside this interval.</li>
<li>In general, <span style="color:dodgerblue"><strong>confidence interval estimates give a range of plausible values for the unknown value of the parameter</strong></span>.</li>
</ul>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<hr>
<p>In <a href="#question-2">Question 2</a>, we created a bootstrap distribution (stored in the vector <code>boot.prop</code>) for the sample proportion of times the ozone concentration exceeds 70 ppb. One possible bootstrap distribution is plotted below. Bootstrap distributions will vary slightly depending on the 100,000 bootstrap resamples that are randomly selected.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.prop,  </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p-hat, sample proportion"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Proportion"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>), <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(boot.prop), <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="17-Bootstrap-Confidence-Int_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="question-3a" class="level3">
<h3 class="anchored" data-anchor-id="question-3a">Question 3a</h3>
<hr>
<p>Using the bootstrap statistics stored in <code>boot.prop</code>, find the lower and upper cutoffs for a 95% bootstrap percentile confidence interval for the proportion of all times the ozone concentration in NYC exceeds 70 ppb.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recall the <code>quantile()</code> function in R. Run the command <code>?quantile</code> for a refresher!</p>
</div>
</div>
<section id="solution-to-question-3a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3a">Solution to Question 3a</h4>
<hr>
<p>Replace all four <code>??</code> in the code cell below with appropriate code. Then run the completed code to compute lower and upper cutoffs for a 95% bootstrap percentile confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 95% bootstrap CI</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>lower.boot<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>upper.boot<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print values to screen</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>lower.boot<span class="fl">.95</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>upper.boot<span class="fl">.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Based on the output above, a 95% bootstrap percentile confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-3b" class="level3">
<h3 class="anchored" data-anchor-id="question-3b">Question 3b</h3>
<hr>
<p>The code cell below plots a bootstrap distribution corresponding of the sample proportions stored in <code>boot.prop</code> along with two blue vertical lines to mark the lower and upper cutoffs for a 95% bootstrap percentile confidence interval. A red vertical line marks the value of the sample proportion we calculated from the original sample.</p>
<p>Run the code cell below to illustrate the confidence interval on the bootstrap distribution. There is nothing to edit in the code cell. Then in the space below, explain the practical meaning of the interval to a person with little to no background in statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">#################################</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code is ready to run!</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># no need to edit the code cell</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="do">#################################</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.prop,  </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p-hat, sample proportion"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Proportion"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>), <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co"># blue lines marking cutoffs</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> lower.boot<span class="fl">.95</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> upper.boot<span class="fl">.95</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="17-Bootstrap-Confidence-Int_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="solution-to-question-3b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3b">Solution to Question 3b</h4>
<hr>
<p>Interpret the confidence interval from <a href="#question-3a">Question 3a</a>.</p>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-3c" class="level3">
<h3 class="anchored" data-anchor-id="question-3c">Question 3c</h3>
<hr>
<p>Sometimes, it is desirable to describe the interval as some value plus or minus some margin of error. Construct a <span style="color:dodgerblue"><strong>symmetric 95% bootstrap confidence interval</strong></span> for the proportion of time the ozone concentration in NYC exceeds 70 ppb. Compare the symmetric confidence interval to your percentile confidence interval in <a href="#question-3a">Question 3a</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recall for normal distributions, approximately 95% of the data is within 2 standard deviations of center of the distribution.</p>
</div>
</div>
<section id="solution-to-question-3c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-3c">Solution to Question 3c</h4>
<hr>
<p>Replace each <code>??</code> in the code cell below with appropriate code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>?? <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>??  <span class="co"># going 2 SE's below the observed sample proportion</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>?? <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>??  <span class="co"># going 2 SE's above the observed sample proportion</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Based on the output above, a symmetric 95% bootstrap confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="adjusting-the-confidence-level" class="level1">
<h1>Adjusting the Confidence Level</h1>
<hr>
<p>We would expect the actual value of the unknown population parameter to equal the corresponding statistic calculated from one of the 100,000 bootstrap resamples in our distribution. Since 95% of the bootstrap statistics are inside the confidence interval:</p>
<blockquote class="blockquote">
<p><strong>A 95% bootstrap percentile confidence interval has about a 95% chance of containing the actual value of the population parameter.</strong></p>
</blockquote>
<p>The <span style="color:dodgerblue"><strong>confidence level</strong></span> is the success rate of success of the interval estimate. We can choose differenet confidence levels for an interval estimate:</p>
<ul>
<li>A 95% confidence level is most common.</li>
<li>Other common confidence levels are 80%, 90%, 99% and 99.9%.</li>
<li>We choose a confidence level. It is not something we calculate.</li>
<li><strong>What happens to an interval estimate when we change the confidence level?</strong></li>
</ul>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<hr>
<p>In <a href="#question-2">Question 2</a>, we created a bootstrap distribution (stored in the vector <code>boot.prop</code>) for the sample proportion of times the ozone concentration exceeds 70 ppb. In <a href="#question-3">Question 3</a>, we used the bootstrap distribution to construct a 95% bootstrap percentile confidence interval. In this question, we will investigate what happens when we change the confidence level.</p>
<section id="question-4a" class="level3">
<h3 class="anchored" data-anchor-id="question-4a">Question 4a</h3>
<hr>
<p>Complete the first code cell below to give a 90% bootstrap percentile confidence interval to estimate the proportion of all time in NYC when the ozone concentration exceeds 70 ppb.</p>
<p>Then complete the second code cell to plot a histogram of the bootstrap distribution from with the upper and lower confidence interval cutoffs marked with vertical lines similar to the plot in <a href="#question-3b">Question 3b</a>.</p>
<section id="solution-to-question-4a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4a">Solution to Question 4a</h4>
<hr>
<p><strong>Based on the output below, a 90% bootstrap percentile confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
<p>Replace all four <code>??</code> in the code cell below with appropriate code. Then run the completed code to compute lower and upper cutoffs for a 90% bootstrap percentile confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 90% bootstrap CI</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>lower.prop<span class="fl">.90</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>upper.prop<span class="fl">.90</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>lower.prop<span class="fl">.90</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>upper.prop<span class="fl">.90</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nothing to edit in the code cell below. Just be sure you first run the code cell above to calculate and store the cutoffs <code>lower.prop.90</code> and <code>upper.prop.90</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">##################################</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code is ready to run!</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># no need to edit the code cell</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="do">##################################</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.prop,  </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p-hat, sample proportion"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Proportion"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>), <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="co"># blue lines marking cutoffs</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> lower.boot<span class="fl">.90</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> upper.boot<span class="fl">.90</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-4b" class="level3">
<h3 class="anchored" data-anchor-id="question-4b">Question 4b</h3>
<hr>
<p>Complete the first code cell below to give a 99% bootstrap percentile confidence interval to estimate the proportion of all time in NYC when the ozone concentration exceeds 70 ppb.</p>
<p>Then complete the second code cell to plot a histogram of the bootstrap distribution from with the upper and lower confidence interval cutoffs marked with vertical lines similar to the plot in <a href="#question-3b">Question 3b</a>.</p>
<section id="solution-to-question-4b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4b">Solution to Question 4b</h4>
<hr>
<p><strong>Based on the output below, a 99% bootstrap percentile confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
<p>Replace all four <code>??</code> in the code cell below with appropriate code. Then run the completed code to compute lower and upper cutoffs for a 90% bootstrap percentile confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 99% bootstrap CI</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>lower.prop<span class="fl">.99</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>upper.prop<span class="fl">.99</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>lower.prop<span class="fl">.99</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>upper.prop<span class="fl">.99</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nothing to edit in the code cell below. Just be sure you first run the code cell above to calculate and store the cutoffs <code>lower.prop.99</code> and <code>upper.prop.99</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">##################################</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># code is ready to run!</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># no need to edit the code cell</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="do">##################################</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.prop,  </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"p-hat, sample proportion"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Sample Proportion"</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed sample proportion</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">mean</span>(nyc.oz <span class="sc">&gt;</span> <span class="dv">70</span>), <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co"># blue lines marking cutoffs</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> lower.boot<span class="fl">.99</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> upper.boot<span class="fl">.99</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-4c" class="level3">
<h3 class="anchored" data-anchor-id="question-4c">Question 4c</h3>
<hr>
<p>When we decreased the confidence level from 95% in <a href="#question-3a">Question 3a</a> to 90% in <a href="#question-4a">Question 4a</a>, did the interval estimate get wider or more narrow? Explain why this makes practical sense. Feel free to explain using the <a href="#sec-fishing">fishing analogy</a> from earlier.</p>
<section id="solution-to-question-4c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4c">Solution to Question 4c</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-4d" class="level3">
<h3 class="anchored" data-anchor-id="question-4d">Question 4d</h3>
<hr>
<p>Explain the trade-off between choosing a confidence level and the precision of the interval estimate. In particular, why would choose a 95% confidence interval over an interval that has a greater chance of success, such as a 99% confidence interval?</p>
<section id="solution-to-question-4d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4d">Solution to Question 4d</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
</section>
<section id="comparing-two-independent-populations" class="level1">
<h1>Comparing Two Independent Populations</h1>
<hr>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="https://static01.nyt.com/images/2020/01/28/well/physed-babies/physed-babies-jumbo.jpg?quality=75&amp;auto=webp" class="img-fluid figure-img" style="width:50.0%" alt="Toddlers"></p>
<figcaption class="figure-caption">Credit: iStock</figcaption>
</figure>
</div>
<p>Often in a study, we may be interested in determining whether there is an association between different variables. For example, we can ask:</p>
<blockquote class="blockquote">
<p>Does smoking during pregnancy have an affect on the weight of the baby at birth?</p>
</blockquote>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<hr>
<p>Explain how you could design a study to collect data that could help determine whether smoking during pregnancy has an affect on the weight of the baby at birth.</p>
<section id="solution-to-question-5" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-5">Solution to Question 5</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
<section id="case-study-smoking-and-birth-weights" class="level1">
<h1>Case Study: Smoking and Birth Weights</h1>
<hr>
<p>To help explore this question, we will use a sample of data in the data frame<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <code>birthwt</code> that is in the package <code>MASS</code> which should already be installed. In the code cell below, the <code>MASS</code> package is loaded and numerical summaries for all variables in <code>birthwt</code> are computed and displayed.</p>
<section id="loading-the-birth-weight-sample" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-birth-weight-sample">Loading the Birth Weight Sample</h2>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)  <span class="co"># load MASS package</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birthwt)  <span class="co"># summary of data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      low              age             lwt             race      
 Min.   :0.0000   Min.   :14.00   Min.   : 80.0   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:19.00   1st Qu.:110.0   1st Qu.:1.000  
 Median :0.0000   Median :23.00   Median :121.0   Median :1.000  
 Mean   :0.3122   Mean   :23.24   Mean   :129.8   Mean   :1.847  
 3rd Qu.:1.0000   3rd Qu.:26.00   3rd Qu.:140.0   3rd Qu.:3.000  
 Max.   :1.0000   Max.   :45.00   Max.   :250.0   Max.   :3.000  
     smoke             ptl               ht                ui        
 Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000  
 Median :0.0000   Median :0.0000   Median :0.00000   Median :0.0000  
 Mean   :0.3915   Mean   :0.1958   Mean   :0.06349   Mean   :0.1481  
 3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.0000  
 Max.   :1.0000   Max.   :3.0000   Max.   :1.00000   Max.   :1.0000  
      ftv              bwt      
 Min.   :0.0000   Min.   : 709  
 1st Qu.:0.0000   1st Qu.:2414  
 Median :0.0000   Median :2977  
 Mean   :0.7937   Mean   :2945  
 3rd Qu.:1.0000   3rd Qu.:3487  
 Max.   :6.0000   Max.   :4990  </code></pre>
</div>
</div>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<hr>
<p>How many observations are in the data set? How many variables? Which variables are categorical and which are quantitative? Which variables are most important in helping determine whether smoking during pregnancy has an affect on the weight of the baby at birth?</p>
<section id="solution-to-question-6" class="level3">
<h3 class="anchored" data-anchor-id="solution-to-question-6">Solution to Question 6</h3>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="cleaning-the-birth-weight-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-the-birth-weight-data">Cleaning the Birth Weight Data</h2>
<hr>
<p>The variable <code>smoke</code> is being stored as a quantitative variable.</p>
<ul>
<li>Pregnant parents that did not smoke have a <code>smoke</code> value equal to <code>0</code>.</li>
<li>Pregnant parents that were smokers have a <code>smoke</code> value equal to <code>1</code>.</li>
<li>Run the code cell below to make these categories more clearly labeled.
<ul>
<li>Non-smokers are assigned a value of <code>no</code>.</li>
<li>Smokers are assigned a value of <code>smoker</code>.</li>
<li>We use the <code>factor()</code> command to convert the <code>smoke</code> variable to a categorical variable.</li>
<li>The output tells us out of 189 parents, 115 self-identified as non-smokers and 74 as smokers.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke[birthwt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="dv">0</span>]  <span class="ot">&lt;-</span> <span class="st">"no"</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke[birthwt<span class="sc">$</span>smoke <span class="sc">==</span> <span class="dv">1</span>]  <span class="ot">&lt;-</span> <span class="st">"smoker"</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>birthwt<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="fu">factor</span>(birthwt<span class="sc">$</span>smoke)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(birthwt<span class="sc">$</span>smoke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    no smoker 
   115     74 </code></pre>
</div>
</div>
</section>
<section id="question-7" class="level2">
<h2 class="anchored" data-anchor-id="question-7">Question 7</h2>
<hr>
<p>Complete the code cell below to create a side-by-side box plots to compare the distribution of weights for smokers and non-smokers.</p>
<section id="solution-to-question-7" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-7">Solution to Question 7</h4>
<hr>
<p>Replace each <code>??</code> in the code cell below to generate side-by-side box plots for comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create side by side box plots</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(?? <span class="sc">~</span> ??, <span class="at">data =</span> ??,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"springgreen4"</span>, <span class="st">"firebrick2"</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Comparison of Birth Weights from Smokers and Non-Smokers"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Smoking Status of Pregnant Parent"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Birth Weight (in grams)"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Non-smoker"</span>, <span class="st">"Smoker"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="difference-in-two-independent-means" class="level2">
<h2 class="anchored" data-anchor-id="difference-in-two-independent-means">Difference in Two Independent Means</h2>
<hr>
<p>Our statistical question is:</p>
<blockquote class="blockquote">
<p>Does smoking during pregnancy have an affect on the weight of the baby at birth?</p>
</blockquote>
<p>In this example, we have two independent populations of parents to consider.</p>
<ul>
<li>All parents that did no smoke during pregnancy.</li>
<li>All parents that smoke during pregnancy.</li>
<li>You are either in one group or the other, not both!</li>
</ul>
<p>Ideally, if we had access to data on every baby that has been born, then we could:</p>
<ul>
<li>Calculate <span class="math inline">\(\mu_{\rm{non}}\)</span>, the mean birth weight of all children of non-smokers.</li>
<li>Calculate <span class="math inline">\(\mu_{\rm{smoker}}\)</span>, the mean birth weight of all children of smokers.</li>
<li>Consider how large is the difference in the two means, <span class="math inline">\(\mu_{\rm{non}} - \mu_{\rm{smoker}}\)</span>.
<ul>
<li>If the difference in populations means is 0, there is no difference in mean birth weights.</li>
<li>If the difference is not 0, then there is a difference in mean birth weights.</li>
</ul></li>
</ul>
<p>We have data from a random sample, but we plug that data in place of the population and perform an equivalent analysis.</p>
<ul>
<li>Calculate <span class="math inline">\(\bar{x}_{\rm{non}}\)</span>, the <em>sample mean</em> birth weight of children of non-smokers in the sample.</li>
<li>Calculate <span class="math inline">\(\bar{x}_{\rm{smoker}}\)</span>, the <em>sample mean</em> birth weight of children of smokers in the sample.</li>
<li>Consider how large is the difference in the two means, <span class="math inline">\(\bar{x}_{\rm{non}} - \bar{x}_{\rm{smoker}}\)</span>.
<ul>
<li>If the difference is <em>close to zero</em>, this indicates there is likely no difference in the population means.</li>
<li>If the difference is <em>not close to zero</em>, this indicates there likely is a difference in the population means.</li>
</ul></li>
</ul>
</section>
<section id="subsetting-the-sample" class="level2">
<h2 class="anchored" data-anchor-id="subsetting-the-sample">Subsetting the Sample</h2>
<hr>
<p>At the moment, we have all of the sample data for smokers and non-smokers stored in the same data frame named <code>birthwt</code>. How can we calculate the sample mean birth weights for the non-smoking group separate from the smoking group? One way to compare the two samples is to split the sample into two independent subsets based on whether or not the child was birthed by a smoker or not.</p>
</section>
<section id="question-8" class="level2">
<h2 class="anchored" data-anchor-id="question-8">Question 8</h2>
<hr>
<p>Answer the questions to find an initial estimate for the difference in the mean birth weights of all children born to a non-smoking parent compared to the mean birth weight of all children born to a parent that did smoke while pregnant.</p>
<section id="question-8a" class="level3">
<h3 class="anchored" data-anchor-id="question-8a">Question 8a</h3>
<hr>
<p>Complete each of the <code>subset()</code> commands below to subset the data into two independent samples: parent was a smoker and parent was a non-smoker.</p>
<section id="solution-to-question-8a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8a">Solution to Question 8a</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset the sample into two independent samples</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>non <span class="ot">&lt;-</span> <span class="fu">subset</span>(??, smoke <span class="sc">==</span> ??)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>smoker <span class="ot">&lt;-</span> <span class="fu">subset</span>(??, smoke <span class="sc">==</span> ??)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-8b" class="level3">
<h3 class="anchored" data-anchor-id="question-8b">Question 8b</h3>
<hr>
<p>Complete the code cell below to calculate, store, and print the difference in sample means based on the data in our original sample.</p>
<section id="solution-to-question-8b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8b">Solution to Question 8b</h4>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate difference in sample means</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>obs.diff <span class="ot">&lt;-</span> ??</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>obs.diff  <span class="co"># print observed difference to screen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br>
<br></p>
</section>
</section>
<section id="question-8c" class="level3">
<h3 class="anchored" data-anchor-id="question-8c">Question 8c</h3>
<hr>
<p>Based on your answer to [Quesiton 8b], given an estimate for the difference in the mean birth weights of all children born to a non-smoking parent compared to the mean birth weight of all children born to a parent that did smoke while pregnant. <em>Include units in your answer.</em></p>
<section id="solution-to-question-8c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8c">Solution to Question 8c</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
<section id="question-8d" class="level3">
<h3 class="anchored" data-anchor-id="question-8d">Question 8d</h3>
<hr>
<p>Based on your estimate in <a href="#question-8c">Question 8c</a>, do you believe there is a difference in the mean birth weight of all babies whose parent smoked while pregnant compared to the mean birth weight of all babies whose parent did not smoke while pregnant?</p>
<section id="solution-to-question-8d" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-8d">Solution to Question 8d</h4>
<p><br><br>
<br><br>
<br></p>
</section>
</section>
</section>
<section id="accounting-for-uncertainty-in-sampling" class="level2">
<h2 class="anchored" data-anchor-id="accounting-for-uncertainty-in-sampling">Accounting for Uncertainty in Sampling</h2>
<hr>
<p>In the case of comparing samples, we do need to be mindful of the randomness involved in the sampling process. If we pick another sample of 189 babies and compare the difference in sample means, we will likely get another value for the difference in sample means. How can we determine whether the difference in sample means is larger than the variability we might expect due to sampling?</p>
</section>
</section>
<section id="bootstrapping-two-independent-samples" class="level1">
<h1>Bootstrapping Two Independent Samples</h1>
<hr>
<p>Given independent samples of sizes <span class="math inline">\(m\)</span> and <span class="math inline">\(n\)</span> from two independent populations:</p>
<ol type="1">
<li>Draw a resample of size <span class="math inline">\(m\)</span> <em>with replacement</em> from the first sample.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>m.non <span class="ot">&lt;-</span> <span class="fu">length</span>(non<span class="sc">$</span>bwt)  <span class="co"># m, size of sample 1</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>temp.non <span class="ot">&lt;-</span> <span class="fu">sample</span>(non<span class="sc">$</span>bwt, <span class="at">size =</span> m.non, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Draw a resample of size <span class="math inline">\(n\)</span> <em>with replacement</em> from the second sample.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>n.smoker <span class="ot">&lt;-</span> <span class="fu">length</span>(smoker<span class="sc">$</span>bwt)  <span class="co"># n, size of sample 2</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>temp.smoker <span class="ot">&lt;-</span> <span class="fu">sample</span>(smoker<span class="sc">$</span>bwt, <span class="at">size =</span> n.smoker, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Compute a statistic that compares the two groups such as a difference or ratio of two statistics (means, proportions, etc.)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>diff.resample <span class="ot">&lt;-</span> <span class="fu">mean</span>(temp.non) <span class="sc">-</span> <span class="fu">mean</span>(temp.smoker)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>diff.resample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 209.3382</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Repeat this process by picking two new resamples (one from each original sample) and compute difference in sample means.</li>
<li>Construct a bootstrap distribution of the comparison statistics (such as a difference of means).</li>
</ol>
<section id="question-9" class="level2">
<h2 class="anchored" data-anchor-id="question-9">Question 9</h2>
<hr>
<p>Follow the steps below to generate a bootstrap distribution for the difference in sample means and obtain a 95% bootstrap percentile confidence interval for the difference in population means.</p>
<section id="question-9a" class="level3">
<h3 class="anchored" data-anchor-id="question-9a">Question 9a</h3>
<hr>
<p>Complete the code cell below to construct a bootstrap distribution for the difference in the sample mean birth weights of of babies born to non-smokers compared to smokers.</p>
<section id="solution-to-question-9a" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9a">Solution to Question 9a</h4>
<hr>
<p>Replace all six <code>??</code> in the code cell below with appropriate code. Then run the completed code to generate a bootstrap distribution and mark the observed sample proportion (in red) and the mean of the bootstrap distribution (in blue) with vertical lines.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>  <span class="co"># Number of bootstrap samples</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>boot.diff.mean <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)  <span class="co"># create vector to store bootstrap proportions</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># for loop that creates bootstrap dist</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  x.non <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  x.smoker <span class="ot">&lt;-</span> <span class="fu">sample</span>(??, <span class="at">size =</span> ??, <span class="at">replace =</span> ??)  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  boot.diff.mean[i] <span class="ot">&lt;-</span> ??  <span class="co"># compute difference in sample means</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co"># plot bootstrap distribution</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.diff.mean,  </span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"x.bar.non - x.bar.smoker (in grams)"</span>,</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution for Difference in Means"</span>)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="co"># red line at the observed  difference in sample means</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"firebrick2"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a><span class="co"># blue line at the center of bootstrap dist</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-9b" class="level3">
<h3 class="anchored" data-anchor-id="question-9b">Question 9b</h3>
<hr>
<p>Complete the code cell below to give a 95% bootstrap percentile confidence interval to estimate the difference in the mean birth weight of all babies born to non-smokers compared the to mean birth of all babies born to smokers.</p>
<section id="solution-to-question-9b" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9b">Solution to Question 9b</h4>
<hr>
<p><strong>Based on the output below, a 95% bootstrap percentile confidence interval is from ?? to ??.</strong></p>
<p><br><br>
<br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find cutoffs for 95% bootstrap CI</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>lower.bwt<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find lower cutoff</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>upper.bwt<span class="fl">.95</span> <span class="ot">&lt;-</span> <span class="fu">quantile</span>(??, <span class="at">probs =</span> ??)  <span class="co"># find upper cutoff</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print to screen</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>lower.bwt<span class="fl">.95</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>upper.bwt<span class="fl">.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-9c" class="level3">
<h3 class="anchored" data-anchor-id="question-9c">Question 9c</h3>
<hr>
<p>Interpret the practical meaning of your interval estimate in <a href="#question-9b">Question 9b</a>. Do you think it is plausible to conclude smoking does have an effect on the weight of a newborn? Explain why or why not.</p>
<section id="solution-to-question-9c" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-9c">Solution to Question 9c</h4>
<hr>
<p><br><br>
<br><br>
<br></p>
<hr>
<p><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" class="img-fluid" alt="Creative Commons License"> <nbsp></nbsp></p>
<p><em>Statistical Methods: Exploring the Uncertain</em> by <a href="https://github.com/CU-Denver-MathStats-OER/Statistical-Theory">Adam Spiegler</a> is licensed under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p>
</section>
</section>
</section>
</section>
<section id="matched-pair-difference-comparing-two-dependent-samples" class="level1">
<h1>Matched-Pair Difference: Comparing Two Dependent Samples</h1>
<hr>
<p>Given <strong>matched samples</strong> each of size <span class="math inline">\(n\)</span>:</p>
<ul>
<li>For each pair calculate the difference.</li>
<li>Consider the collection of <span class="math inline">\(n\)</span> differences as your original sample.</li>
<li>Draw a resample of size <span class="math inline">\(n\)</span> with replacement from the sample of differences. Compute the relevant statistic.</li>
<li>Repeat this many times.</li>
<li>Construct the bootstrap distribution of the statistic.</li>
</ul>
<p><strong>We do a resample of the differences of each pair as opposed to two resamples from each individual sample.</strong></p>
</section>
<section id="case-study-darwin-cross-fertilization-experiments" class="level1">
<h1>Case Study: Darwin Cross-Fertilization Experiments</h1>
<p>The data frame <code>darwin.maize</code> in the <code>agridat</code> package contains results from experiment<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> by Charles Darwin in 1876.</p>
<section id="loading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data">Loading the Data</h2>
<hr>
<p>It is very likely you do not have the package <code>agridat</code> installed. You will need to first install the <code>agridat</code> package.</p>
<ul>
<li>Go to the R Console window.</li>
<li>Run the command <code>&gt; install.packages("agridat")</code>.</li>
</ul>
<p>You will only need to run the <code>install.package()</code> command one time. You can now access <code>agridat</code> anytime you like! However, you will need to run the command <code>library(agridat)</code> during any R session in which you want to access data from the <code>agridat</code> package. <strong>Be sure you have first installed the <code>agridat</code> package before executing the code cell below.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># be sure you have already installed the agridat package</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agridat)  <span class="co"># loading agridat package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="summarizing-and-storing-the-data-1" class="level3">
<h3 class="anchored" data-anchor-id="summarizing-and-storing-the-data-1">Summarizing and Storing the Data</h3>
<hr>
<p>The the help manual for the data frame <code>darwin.maize</code> has a nice summary of the experiment and the data. Run the code cell below to learn about the data and context of the experiment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># be sure you have already loaded the agridat package</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>?darwin.maize</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Below is an excerpt from the help manual:</p>
<blockquote class="blockquote">
<p>Charles Darwin, in 1876, reported data from an experiment that he had conducted on the heights of corn plants. The seeds came from the same parents, but some seeds were produced from self-fertilized parents and some seeds were produced from cross-fertilized parents. Pairs of seeds were planted in pots. Darwin hypothesized that cross-fertilization produced produced more robust and vigorous offspring.</p>
</blockquote>
<p>In the code cell below we provide a numerical summary of the two variables in the sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(darwin.maize)  <span class="co"># numerical summary of each variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  pot          pair       type        height     
 I  : 6   a      : 2   cross:15   Min.   :12.00  
 II : 6   b      : 2   self :15   1st Qu.:17.53  
 III:10   c      : 2              Median :18.88  
 IV : 8   d      : 2              Mean   :18.88  
          e      : 2              3rd Qu.:21.38  
          f      : 2              Max.   :23.50  
          (Other):18                             </code></pre>
</div>
</div>
<ul>
<li><code>pot</code> is a categorical variable with 4 levels: <code>I</code>, <code>II</code>, <code>III</code>, and <code>IV</code>.<br>
</li>
<li><code>pair</code> is a categorical variable with 15 levels: <code>a</code>, <code>b</code>, <span class="math inline">\(\ldots\)</span> , <code>n</code>, <code>o</code>.</li>
<li><code>type</code> cagtegorical with 2 levels: <code>cross</code> and <code>self</code>.</li>
<li><code>height</code> plant height in inches</li>
</ul>
<p>The code cell below displays the distribution of mandible lengths separately for males and females.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># side by side box plots</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> type, <span class="at">data =</span> darwin.maize, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"dodgerblue"</span>, <span class="st">"mediumseagreen"</span>),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Darwin Cross Fertilization Results"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Hength (in inches)"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="17-Bootstrap-Confidence-Int_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="wranginling-the-data" class="level2">
<h2 class="anchored" data-anchor-id="wranginling-the-data">Wranginling the Data</h2>
<hr>
<p>In the code cell below, we reorganize the data from <code>corn.maize</code> so it is structured in a way that will be more convenient for our analysis. The result is stored in a new data frame named <code>corn</code>, and the first 6 rows are printed to the screen. In total, there are 18 pairs of data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>self <span class="ot">&lt;-</span> <span class="fu">subset</span>(darwin.maize, <span class="at">select =</span> <span class="fu">c</span>(pair, type, height), type <span class="sc">==</span> <span class="st">"self"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>cross <span class="ot">&lt;-</span> <span class="fu">subset</span>(darwin.maize, <span class="at">select =</span> <span class="fu">c</span>(pair, type, height), type <span class="sc">==</span> <span class="st">"cross"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>corn <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>], self<span class="sc">$</span>height, cross<span class="sc">$</span>height)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(corn) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pair"</span>, <span class="st">"self"</span>, <span class="st">"cross"</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(<span class="fu">head</span>(corn, <span class="dv">18</span>), <span class="at">format =</span> <span class="st">"html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-corn" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Table&nbsp;16.1: Corn Heights</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">pair</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">self</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">cross</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">17.375</td>
<td style="text-align: right;">23.500</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">20.375</td>
<td style="text-align: right;">12.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">c</td>
<td style="text-align: right;">20.000</td>
<td style="text-align: right;">21.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">d</td>
<td style="text-align: right;">20.000</td>
<td style="text-align: right;">22.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">e</td>
<td style="text-align: right;">18.375</td>
<td style="text-align: right;">19.125</td>
</tr>
<tr class="even">
<td style="text-align: left;">f</td>
<td style="text-align: right;">18.625</td>
<td style="text-align: right;">21.500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">g</td>
<td style="text-align: right;">18.625</td>
<td style="text-align: right;">22.125</td>
</tr>
<tr class="even">
<td style="text-align: left;">h</td>
<td style="text-align: right;">15.250</td>
<td style="text-align: right;">20.375</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i</td>
<td style="text-align: right;">16.500</td>
<td style="text-align: right;">18.250</td>
</tr>
<tr class="even">
<td style="text-align: left;">j</td>
<td style="text-align: right;">18.000</td>
<td style="text-align: right;">21.625</td>
</tr>
<tr class="odd">
<td style="text-align: left;">k</td>
<td style="text-align: right;">16.250</td>
<td style="text-align: right;">23.250</td>
</tr>
<tr class="even">
<td style="text-align: left;">l</td>
<td style="text-align: right;">18.000</td>
<td style="text-align: right;">21.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">m</td>
<td style="text-align: right;">12.750</td>
<td style="text-align: right;">22.125</td>
</tr>
<tr class="even">
<td style="text-align: left;">n</td>
<td style="text-align: right;">15.500</td>
<td style="text-align: right;">23.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o</td>
<td style="text-align: right;">18.000</td>
<td style="text-align: right;">12.000</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</section>
<section id="question-4-wetsuit-case-study" class="level2">
<h2 class="anchored" data-anchor-id="question-4-wetsuit-case-study">Question 4: Wetsuit Case Study</h2>
<hr>
<p>Example 20.5. Researchers are concerned about the impact of vitamin C content reduction due to storage and ship- ment. To test this, researchers randomly chose a collection of bags of wheat soy blend bound for Haiti, marked them, and measured vitamin C from a sample of the contents. Five months later, the bags were opened and a second sample was measured for vitamin C content. The units are milligrams of vitamin C per 100g of wheat soy blend. - Watkins page 366</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://drive.google.com/uc?export=view&amp;id=10yVZWIbY_JwXzTylbPEq1rOpair1B3uO.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Phelps Wetsuit</figcaption>
</figure>
</div>
<p>In the 2008 Olympics there was a lot of controversy over new swimsuits that possibly provided an unfair advantage to swimmers which led to new international rules regarding swimsuit materials and coverage. <strong>Can a swimsuit really make a swimmer faster?</strong><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>A study<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> tested whether wearing wetsuits influences swimming velocity. Twelve competitive swimmers swam 1500 meters at maximum speed twice each.</p>
<ul>
<li>Once wearing a wetsuit and once wearing a regular bathing suit.</li>
<li>The order of the trials was randomized.</li>
<li>Each time, the maximum velocity in meters/sec of the swimmer was recorded.</li>
<li>The max velocity with and without the wetsuit are recorded in the table below.</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Swimmer</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
<th>11</th>
<th>12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>New Wetsuit</td>
<td><span class="math inline">\(1.57\)</span></td>
<td><span class="math inline">\(1.47\)</span></td>
<td><span class="math inline">\(1.42\)</span></td>
<td><span class="math inline">\(1.35\)</span></td>
<td><span class="math inline">\(1.22\)</span></td>
<td><span class="math inline">\(1.75\)</span></td>
<td><span class="math inline">\(1.64\)</span></td>
<td><span class="math inline">\(1.57\)</span></td>
<td><span class="math inline">\(1.56\)</span></td>
<td><span class="math inline">\(1.53\)</span></td>
<td><span class="math inline">\(1.49\)</span></td>
<td><span class="math inline">\(1.51\)</span></td>
</tr>
<tr class="even">
<td>Regular Swimsuit</td>
<td><span class="math inline">\(1.49\)</span></td>
<td><span class="math inline">\(1.37\)</span></td>
<td><span class="math inline">\(1.35\)</span></td>
<td><span class="math inline">\(1.27\)</span></td>
<td><span class="math inline">\(1.12\)</span></td>
<td><span class="math inline">\(1.64\)</span></td>
<td><span class="math inline">\(1.59\)</span></td>
<td><span class="math inline">\(1.52\)</span></td>
<td><span class="math inline">\(1.50\)</span></td>
<td><span class="math inline">\(1.45\)</span></td>
<td><span class="math inline">\(1.44\)</span></td>
<td><span class="math inline">\(1.41\)</span></td>
</tr>
<tr class="odd">
<td>Difference</td>
<td><span class="math inline">\(0.08\)</span></td>
<td><span class="math inline">\(0.10\)</span></td>
<td><span class="math inline">\(0.07\)</span></td>
<td><span class="math inline">\(0.08\)</span></td>
<td><span class="math inline">\(0.10\)</span></td>
<td><span class="math inline">\(0.11\)</span></td>
<td><span class="math inline">\(0.05\)</span></td>
<td><span class="math inline">\(0.05\)</span></td>
<td><span class="math inline">\(0.06\)</span></td>
<td><span class="math inline">\(0.08\)</span></td>
<td><span class="math inline">\(0.05\)</span></td>
<td><span class="math inline">\(0.10\)</span></td>
</tr>
</tbody>
</table>
<section id="question-4a-1" class="level3">
<h3 class="anchored" data-anchor-id="question-4a-1">Question 4a</h3>
<hr>
<p>The code cell below contains ordered vectors of maximum velocities (with the wetsuit and with a regular swimsuit) for each of the 12 swimmers. The ordering in each vector must be consistent since we have natural pairing of values between the two samples. Compute the observed mean matched-pair difference.</p>
<section id="solution-to-question-4a-1" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4a-1">Solution to Question 4a</h4>
<hr>
<p>Complete the code cell below by replacing each <code>??</code> with appropriate code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vectors containing the times of each swimmer. Ordering is critical</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>wetsuit <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.57</span>, <span class="fl">1.47</span>, <span class="fl">1.42</span>, <span class="fl">1.35</span>, <span class="fl">1.22</span>, <span class="fl">1.75</span>, <span class="fl">1.64</span>, <span class="fl">1.57</span>, <span class="fl">1.56</span>, <span class="fl">1.53</span>, <span class="fl">1.49</span>, <span class="fl">1.51</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>none <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.49</span>, <span class="fl">1.37</span>, <span class="fl">1.35</span>, <span class="fl">1.27</span>, <span class="fl">1.12</span>, <span class="fl">1.64</span>, <span class="fl">1.59</span>, <span class="fl">1.52</span>, <span class="fl">1.50</span>, <span class="fl">1.45</span>, <span class="fl">1.44</span>, <span class="fl">1.41</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>Diff <span class="ot">&lt;-</span> ??  <span class="co"># compute vector of matched-pair differences</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>obs.match <span class="ot">&lt;-</span> ??  <span class="co"># compute mean of matched-pair differences</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print to screen</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>obs.match</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-4b-1" class="level3">
<h3 class="anchored" data-anchor-id="question-4b-1">Question 4b</h3>
<hr>
<p>Generate one possible bootstrap resample and print the values in your resample to the screen.</p>
<section id="solution-to-question-4b-1" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4b-1">Solution to Question 4b</h4>
<hr>
<p>Complete the code cell below by replacing each <code>??</code> with appropriate code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(??, ??, <span class="at">replace =</span> ??)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-4c-1" class="level3">
<h3 class="anchored" data-anchor-id="question-4c-1">Question 4c</h3>
<hr>
<p>Construct a 95% bootstrap percentile confidence interval to estimate this difference.</p>
<section id="solution-to-question-4c-1" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4c-1">Solution to Question 4c</h4>
<hr>
<p>Complete the code cell below by replacing each <code>??</code> with appropriate code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(Diff) <span class="co"># number of matched-pairs in sample</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>boot.match <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bootstrap samples by picking n difference from original sample</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="co"># With replacement, and then find mean of those differences.</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  samp.diff <span class="ot">&lt;-</span> ??  <span class="co"># pick a bootstrap resample</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  boot.match[i] <span class="ot">&lt;-</span> ??  <span class="co"># compute mean of resampled matched-pair differences</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap mean and bootstrap standard error</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>mean.match <span class="ot">&lt;-</span> ??  <span class="co"># compute bootstrap mean</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>se.match <span class="ot">&lt;-</span> ??  <span class="co"># compute bootstrap standard error</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate lower and upper cutoffs</span></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a><span class="co"># for the 95% Bootstrap CI</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>lower.match <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot.match, <span class="at">probs =</span> ??)</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>upper.match <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot.match, <span class="at">probs =</span> ??)</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>lower.match</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>upper.match</span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Display bootstrap distribution</span></span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot.match, <span class="at">xlab =</span> <span class="st">"difference in max velocity in m/sec (wetsuit - none)"</span>,</span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">"Bootstrap Dist for Mean Matched-Pair Difference (n=12)"</span>)</span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a red line at the observed mean matched-pair difference</span></span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Add blue lines at cutoffs for 95 percentile</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ??, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-4d-1" class="level3">
<h3 class="anchored" data-anchor-id="question-4d-1">Question 4d</h3>
<hr>
<p>Interpret the practical meaning of your answer to <a href="#question-4c">Question 4c</a>. Do you think it is plausible to conclude the wetsuit gives a competitive advantage? Explain why or why not.</p>
<section id="solution-to-question-4d-1" class="level4">
<h4 class="anchored" data-anchor-id="solution-to-question-4d-1">Solution to Question 4d</h4>
<hr>
<p><br>
<br>
<br>
</p>


</section>
</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><a href="https://www.epa.gov/ozone-pollution-and-your-patients-health/what-ozone" class="uri">https://www.epa.gov/ozone-pollution-and-your-patients-health/what-ozone</a> accessed June 26, 2023<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="https://www.epa.gov/naaqs/ozone-o3-air-quality-standards">Ozone Air Quality Standards acccessed from EPA June 26, 2023</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Bruntz, Cleveland, Kleiner, and Warner. (1974). “The Dependence of Ambient Ozone on Solar Radiation, Wind, Temperature, and Mixing Height”. In <em>Symposium on Atmospheric Diffusion and Air Pollution</em>. American Meterological Society, Boston.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Answers from <a href="#question-2">Question 2</a> may vary<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Baystate Medical Center, Springfield, Massachusetts<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Darwin, C. R. 1876. “The effects of cross and self fertilisation in the vegetable kingdom”. London: John Murray.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Based on content from Statistics: <em>Unlocking the Power of Statistics</em> by R. Lock, P. Lock, K. Lock, E. Lock, and D. Lock.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>de Lucas, Balidan, Neiva, Grecco, and Denadai. “The effects of wetsuits on physiological and biomechanical indices during swimming’’, <em>Journal of Science and Medicine in Sport</em>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./16-Bootstrap-Dist.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">5.1: Bootstrap Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./18-Bootstrap-Other-Stats.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">5.3: Bootstrapping Comparitive Statistics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Statistical Methods: Exploring the Uncertain by Adam Spiegler</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right"><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" class="img-fluid" alt="Creative Commons License"> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-N-SA 4.0</a></div>
  </div>
</footer>



</body></html>